#!/bin/sh -e

if test "$1" = "configure"; then
    if dpkg --compare-versions "$2" lt-nl 1:2.3.14-3; then
        sed -i -e "s/INETD_COMPAT=Yes/INETD_COMPAT=No/" /etc/default/xinetd
    fi
fi

if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
    invoke-rc.d xinetd stop
elif [ -x /etc/init.d/xinetd ]; then
    /etc/init.d/xinetd stop >&2
else
    start-stop-daemon --quiet --stop --signal 3 --oknodo --exec /usr/sbin/xinetd
fi

#DEBHELPER#
